services:
  attacker-server:
    build: server
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    ports:
      - "3000:3000"
  attacker-client:
        build:
          context: client
          args:
            - VITE_SERVER_HOST=http://${HOST_IP}:3000
        networks:
          - app_net
        ports:
          - "8080:8080"
  victim:
        environment:
          - SERVER_HOST=attacker-server
        build: .
        networks:
          - app_net
        ports:
          - "5000:5000"


networks:
  app_net:
    ipam:
      driver: default
      config:
        # The IP address range 172.16.0.0 to 172.31.255.255 is reserved by the IANA for private networks. Choose any within this range as long as it doesn't conflict with other networks on your Docker host.
        - subnet: 172.16.238.0/24